// Site configuration - Update this when domain changes
export const siteConfig = {
  name: "Dimsure",
  description:
    "A public, community-powered database of box dimensions for products. Optimize your packaging and logistics with verified data.",
  url: "https://dimsure.online",
  ogImage: "https://dimsure.online/og-image.png",
  creator: "Dimsure Team",
  keywords: [
    "packaging dimensions",
    "box measurements",
    "logistics",
    "shipping",
    "product dimensions",
    "package size",
    "shipping calculator",
    "box dimensions",
    "box size",
    "box size calculator",
    "box size estimator",
    "box fit calculator",
    "amazon box dimensions",
    "amazon box measurements",
    "amazon box size",
    "amazon box size calculator",
    "amazon box size estimator",
    "amazon box fit calculator",
    "apple box dimensions",
    "apple box measurements",
    "apple box size",
    "apple box size calculator",
    "apple box size estimator",
    "apple box fit calculator",
    "samsung box dimensions",
    "samsung box measurements",
    "samsung box size",
    "samsung box size calculator",
    "samsung box size estimator",
    "samsung box fit calculator",
    "meta box dimensions",
    "meta box measurements",
    "meta box size",
    "meta box size calculator",
    "meta box size estimator",
    "meta box fit calculator",
  ],
  links: {
    twitter: "https://twitter.com/dimsure_app",
  },
}
